version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm start"

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    ports:
      - "3001:8080"
    depends_on:
      - backend

  studio:
    build: ./backend
    command: npx prisma studio
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "5555:5555"
    depends_on:
      - db

volumes:
  pgdata: 